### ISSUE TITLE
Code blocks leave ugly trailing blank lines

### ISSUE THREAD

**Issue by MaxWilson** [fsprojects/FSharp.Formatting#644]
I was adding documentation to fsharp-core-docs and at dsyme's suggestion I formatted the code blocks like so:

```
    /// <example>
    /// <code>
    ///     None |> Option.toList // evaluates to []
    ///     Some 42 |> Option.toList // evaluates to [42]
    /// </code>
    /// </example>
```

Unfortunately it seems that that leaves ugly whitespace at the end of the code block (and I'm not wild about the indented left margin either). Partial screenshot:

![image](https://user-images.githubusercontent.com/6829565/107895408-15ac1800-6ee8-11eb-9239-f5848dd41a1f.png)

Ideally fsdocs would trim the trailing whitespace within the code block, and also normalize left-indentation so that the outermost indented block isn't indented.

**Known workaround**

I can format my code-in-comments without whitespace within the code block:

```
    /// <example>
    /// <code>None |> Option.toList // evaluates to []
    ///Some 42 |> Option.toList // evaluates to [42]</code>
    /// </example>
```

That is tremendously ugly though, especially lack of spacing on the third line before "Some 42". The output looks nicer though (partial screenshot):

![image](https://user-images.githubusercontent.com/6829565/107895383-0036ee00-6ee8-11eb-8e6b-39cf630c71af.png)

**Comment by dsyme** [comment]
Fixed in 9.0.4 by #653

**Comment by nhirschey** [comment]
Thanks for pointing out @MaxWilson, this poor formatting is caused by PR #762 from @yazeedobaid.

Deleting the HTML added by that PR fixes the formatting. Thoughts @yazeedobaid?

![html-element](https://user-images.githubusercontent.com/5226115/202325659-6c5f5d49-34da-44fb-a5af-bbc02a98b80a.gif)

**Comment by yazeedobaid** [comment]
@nhirschey I looked at PR #762 and the trim for the new line still exists. Please see [this line](https://github.com/yazeedobaid/FSharp.Formatting/blob/0c090e95f98ab4407b7b844284e9c449e74d617d/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L1890). Maybe it is caused by a css rule that got applied after the addition of the `code` element inside the `pre` element?
